apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
        - name: delivery
          image: thefoodhubmicroservice-delivery-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
          env:
            - name: DB
              value: "mongodb+srv://prabashwara65:Hwd6vJ69Fx6rhTwP@cluster0.n7bqx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
            - name: PORT
              value: "4002"
            - name: TOKEN
              value: "TheFoodHubJWT_Token_sdasdasdasdada"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIA5FTZCDBRPZZOERPB"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: AWS_REGION
              value: "eu-north-1"
            - name: AWS_S3_BUCKET
              value: "food-hub-hasara"
            - name: STRIPE_SECRET_KEY
              value: "sk_test_51RHR0rGh4o63MbLiFNiYYOcVEEEyeEqWHVwL0Q0klO46wGX9vQJG1Wuwhu4g5QwZvxjss7usReNE5xcsHTfBHTUc00BN8jaEzX"
            - name: STRIPE_WEBHOOK_SECRET
              value: "whsec_22f0a33badbc5cc11de8726e07b47b5680d65cf002021d9b0e750dd90dabdd43"
            - name: GOOGLE_MAPS_API_KEY
              value: "AIzaSyAnjsdMyhOrZEXpYMA1faKFR1QkHwyNsHY"
            - name: EMAIL_USER
              value: "therath2426@gmail.com"
            - name: EMAIL_PASS
              value: "xwnecenewysxurzk"


---
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  type: NodePort
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4002
      nodePort: 30002  
